version: '1.29.2'
services:
  redis:
    image: redis:alpine
    command: 
      - redis-server
    restart: on-failure
    ports:
      - "6379:6379"
    db:
      image: nouchka/sqlite3:latest
      stdin_open: true
      tty: true
      volumes:
        - ./db/:/root/db/
      restart: on-failure
      ports:
        - "5432:5432"
    bot:
      build: .
      command: sh -c "make migrate && python -m bot"
      restart: always
      depends_on:
        - db
        - redis

volumes:
  pgdata: